<?xml version="1.0"?>

<!--This starts the DTD. The first four lines address document structure -->
<!DOCTYPE list [
   <!ELEMENT list (recipe*)>
   <!ELEMENT recipe (author, recipe_name, meal, course, ingredients,
             directions)>
   <!ELEMENT ingredients (item+)>
   <!ELEMENT meal (#PCDATA)>
   <!ELEMENT course (#PCDATA)>
   <!ELEMENT item (#PCDATA|sub_item)*>
   <!--These are the remaining elements of the recipe tag -->
   <!ELEMENT recipe_name (#PCDATA)>
   <!ELEMENT author (#PCDATA)>
   <!ELEMENT directions (#PCDATA)>
   <!--The remaining element of the item tag -->
   <!ELEMENT sub_item (#PCDATA)>
]>

<list>
   <recipe>
      <author>Carol Schmidt</author>
      <recipe_name>Chocolate Chip Bars</recipe_name>
      <meal>Dinner</meal>
      <course>Dessert</course>
      <ingredients>
         <item>2/3 C butter</item>
         <item>2 C brown sugar</item>
         <item>1 tsp vanilla</item>
         <item>1 3/4 C unsifted all-purpose flour</item>
         <item>1 1/2 tsp baking powder</item>
         <item>1/2 tsp salt</item>
         <item>3 eggs</item>
         <item>1/2 C chopped nuts</item>
         <item>2 cups (12-oz pkg.) semi-sweet choc. chips</item>
      </ingredients>
      <directions>
Preheat oven to 350 degrees. Melt  butter; combine
with brown sugar and vanilla in large mixing bowl.

Set aside to cool.  Combine flour, baking powder, and
salt; set aside.

Add eggs to cooled sugar mixture; beat well.  Stir in
reserved dry ingredients, nuts, and chips.

Spread in greased 13-by-9-inch pan. Bake for 25 to 30
minutes until golden brown; cool.  Cut into squares.
      </directions>
   </recipe>
   <recipe>
     <author>Carol Schmidt</author>
     <recipe_name>Pasta with tomato Sauce</recipe_name>
     <meal>Dinner</meal>
     <course>Entree</course>
     <ingredients>
        <item>1 lb spaghetti</item>
        <item>1 16-oz can diced tomatoes</item>
        <item>4 cloves garlic</item>
        <item>1 diced onion</item>
        <item>Italian seasoning
           <sub_item>oregano</sub_item>
           <sub_item>basil</sub_item>
           <sub_item>crushed red pepper</sub_item>
        </item>
     </ingredients>
     <directions>
Boil pasta. Saute garlic and onion. Add tomatoes.
Serve hot.
     </directions>
  </recipe>
</list>
